theme: jekyll-theme-cayman
markdown: kramdown
highlighter: rouge

title: Catroweb API Documentation
description: How to use the Web API of the pocketcode website

kramdown:
  input: GFM
  hard_wrap: false
